plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version '2.15.0'
}

group = 'org.aptkode'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity("2025.1")
        bundledPlugin("com.intellij.java")
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}